

platform:ios, '17.0'
 
target 'MVP模式' do
  pod 'Masonry', '~> 1.1.0'
  pod 'LookinServer', :configurations => ['Debug']
  pod 'AFNetworking', '~> 4.0'
  pod 'YYModel'
  pod 'SDWebImage', '~> 5.0'
  pod 'WCDB.objc'
end