

platform :ios, '13.0'
use_modular_headers!

target 'Spotify' do
  use_frameworks! :linkage => :static

  pod 'Masonry', '~> 1.1.0'
  pod 'LookinServer', :configurations => ['Debug']
  pod 'AFNetworking', '~> 4.0'
  pod 'YYModel'
  pod 'SDWebImage', '~> 5.0'
  pod 'WCDB.objc'
end